title: "IlHarper's Blog"
# subtitle: ''
description: '耳を澄ましてはいけません。'
keywords: ilharper
author: Il Harper
# language: 'zh-CN'
timezone: ''

url: https://ilharper.vbox.moe
pretty_urls:
  trailing_index: false
  trailing_html: false

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
skip_render:

default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false

index_generator:
  path: ''
  per_page: 15
  order_by: -date
  single_language_index: false

default_category: uncategorized
category_map:
tag_map:

meta_generator: true

date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: 'mtime'

per_page: 15
pagination_dir: page

include:
exclude:
ignore:

theme: next

deploy:
  type: git
  repo:
    github:
      url: https://github.com/Afanyiyu/ilharper-vbox-moe.git
      branch: master
      token: $VERCEL_DEPLOY_TOKEN
  message: 'IlHarper Blog Deploy'
  name: 'Il Harper'
  email: 'afanyiyu@hotmail.com'

# I18n
language:
  - en
  - zh-CN
i18n_dir: :lang
i18n:
  type:
    - page
    # - post
  generator:
    - archive
    - category
    - tag
    - index

permalink_defaults:
  lang: en
permalink: :lang/:title/
# permalink: :title/
new_post_name: :lang/:title.md

filter_optimize:
  enable: false
  remove_comments: false
  css:
    minify: true
    bundle: true
    delivery: true
  js:
    minify: true
    bundle: true
  priority: 12

search:
  path: search.xml
  field: post
  content: true
  format: html

all_minifier: true
image_minifier:
  enable: false

marked:
  smartypants: false
