scheme: Gemini
minify: true
darkmode: true

favicon:
  small: /images/favicon/favicon-16x16.png
  medium: /images/favicon/favicon-32x32.png
  apple_touch_icon: /images/favicon/apple-touch-icon.png
  safari_pinned_tab: /images/favicon/safari-pinned-tab.svg

creative_commons:
  license: by-nc-sa
  sidebar: true
  post: true

menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  # sitemap: /sitemap.xml

menu_settings:
  icons: true
  badges: false

sitemap:
  path: sitemap.xml
  rel: false
  tags: true
  categories: true

tagcloud:
  min: 12 # Minimun font size in px
  max: 30 # Maxium font size in px
  amount: 200 # Total amount of tags
  orderby: name # Order of tags
  order: 1 # Sort order

footer:
  powered: false

# post_meta:
#   updated_at:
#     enable: false

# Reward
reward_settings:
  enable: true
  animation: false
  comment: Buy me a coffee
reward:
  wechatpay: /images/pay/wechatpay.png
  alipay: /images/pay/alipay.png
  # bitcoin: /images/pay/bitcoin.png

preconnect: true
pjax: true
fancybox: false
mediumzoom: true
quicklink:
  enable: true
motion:
  enable: false
nprogress:
  enable: true

codeblock:
  theme:
    light: vs2015
    dark: vs2015
  copy_button:
    enable: true

back2top:
  enable: true
  scrollpercent: true
bookmark:
  enable: true
  # color: "#222"
  save: manual

# I18n
language_switcher: true
cache:
  enable: false

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: false
  preload: false

vendors:
  internal: jsdelivr
  plugins: jsdelivr
  anime:
  fontawesome:

index_with_subtitle: true
