name: 'Build and Deploy'

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Clean
      uses: heowc/action-hexo@main
      with:
        args: clean
    - name: Generate
      uses: heowc/action-hexo@main
      with:
        args: generate
    - name: Deploy
      uses: heowc/action-hexo@main
      env:
        EMAIL: afanyiyu@hotmail.com
        NAME: 'Il Harper'
        VERCEL_DEPLOY_TOKEN: ${{ secrets.VERCEL_DEPLOY_TOKEN }}
      with:
        args: deploy
